[project]
name = "tarp"
version = "0.1.0"
description = "TARP - A deep learning tool for predicting antimicrobial resistance from nucleotide sequences"
authors = [{ name = "Joel Jacob", email = "j7.jacob@hdr.qut.edu.au" }]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["antimicrobial resistance", "deep learning", "bioinformatics", "machine learning"]
requires-python = ">=3.12"

dependencies = [
    "polars",                   # Data manipulation
    "numpy",                    # Numerical operations
    "scikit-learn",             # Machine learning utilities
    "torch",                    # Deep learning
    "transformers",             # Pre-trained models and tokenizers
    "tokenizers",               # Efficient tokenization
    "tqdm",                     # Progress bars
    "plotly",                   # Interactive visualizations
    "pyarrow",                  # Efficient data storage and retrieval
    "scipy",                    # Scientific computing
    "biopython",                # Biological sequence handling
    "safetensors",              # Safe and efficient model storage
    "torcheval",                # PyTorch model evaluation
    "iterative-stratification", # Multilabel classification utilities
    "pydantic-settings",        # Settings management
    "xgboost",                  # Gradient boosting
    "odyssey",                  # Custom library for TARP
]

[project.scripts]
tarp = "tarp.app:main"

[project.urls]
repository = "https://github.com/debugst1ck/tarp"
issues = "https://github.com/debugst1ck/tarp/issues"

[tool.uv]
package = true

[tool.uv.sources]
odyssey = { workspace = true }

[tool.uv.workspace]
members = ["lib/odyssey"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
