[project]
name = "tarp"
version = "0.1.0"
description = "TARP - A deep learning tool for predicting antimicrobial resistance from nucleotide sequences"
authors = [{ name = "Joel Jacob", email = "j7.jacob@hdr.qut.edu.au" }]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["antimicrobial resistance", "deep learning", "bioinformatics", "machine learning"]
requires-python = ">=3.12"

dependencies = [
    "polars",                   # Data manipulation
    "numpy",                    # Numerical operations
    "scikit-learn",             # Machine learning utilities
    "torch",                    # Deep learning
    "transformers",             # Pre-trained models and tokenizers
    "tokenizers",               # Efficient tokenization
    "tqdm",                     # Progress bars
    "plotly",                   # Interactive visualizations
    "pyarrow",                  # Efficient data storage and retrieval
    "scipy",                    # Scientific computing
    "biopython",                # Biological sequence handling
    "safetensors",              # Safe and efficient model storage
    "torcheval",                # PyTorch model evaluation
    "iterative-stratification", # Multilabel classification utilities
    "xgboost",                  # Quick classification
]

[project.scripts]
tarp = "tarp.app:main"

[tool.uv]
package = true

[project.urls]
Repository = "https://github.com/debugst1ck/TARP"
Issues = "https://github.com/debugst1ck/TARP/issues"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[dependency-groups]
dev = ["ruff", "pytest"]
jupyter = ["ipykernel", "nbformat", "ipywidgets"]
plmarg = ["xgboost"]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

# Pytest in the tests/ directory and subdirectories
[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--maxfail=5"

[tool.basedpyright]
reportMissingTypeStubs = false
exclude = [
    ".git",
    "__pycache__/",
    "*.egg-info/",
    "*.py[cod]",
    ".venv",
    "temp/data/external/sequences/",
]
