from abc import ABC

from tarp.training.context import TrainerContext
from tarp.typed.training import ModelT


class Callback(ABC):
    def on_epoch_end(self, context: TrainerContext[ModelT]) -> None: ...

    def on_training_end(self, context: TrainerContext[ModelT]) -> None: ...

    def on_training_start(self, context: TrainerContext[ModelT]) -> None: ...

    def on_epoch_start(self, context: TrainerContext[ModelT]) -> None: ...

    def on_train_batch_end(self, context: TrainerContext[ModelT]) -> None: ...

    def on_train_batch_start(self, context: TrainerContext[ModelT]) -> None: ...

    def on_validation_batch_end(self, context: TrainerContext[ModelT]) -> None: ...

    def on_validation_batch_start(self, context: TrainerContext[ModelT]) -> None: ...

    def after_optimizer_step(self, context: TrainerContext[ModelT]) -> None: ...
