from abc import ABC, abstractmethod


class Logger(ABC):
    """Abstract base interface for all framework loggers."""

    @abstractmethod
    def debug(self, message: str) -> None: ...
    @abstractmethod
    def info(self, message: str) -> None: ...
    @abstractmethod
    def warning(self, message: str) -> None: ...
    @abstractmethod
    def error(self, message: str) -> None: ...
    @abstractmethod
    def critical(self, message: str) -> None: ...
    @abstractmethod
    def exception(self, message: str, exc_info: bool = True) -> None: ...
